### ISSUE TITLE
Station numbers for group1 subsequent rounds return 1

### ISSUE THREAD

**Issue by LarsJohanFolde** [Goosly/wca-scorecards#40]
When printing station numbers in later rounds everyone in group 1 will always be placed on timer 1. It seems to be an issue with the last commit where the following line was changed:

`scorecard.group = Math.floor(i * config.numberOfGroups / round.results.length) + 1;`

**Comment by Goosly** [comment]
Fixed in https://github.com/Goosly/wca-scorecards/commit/adcc666088134a702f11839cd308cee935fcea04

Thanks for letting me know!
