### ISSUE TITLE
Allowing non-organizers to print scorecards

### ISSUE THREAD

**Issue by IldenH** [Goosly/wca-scorecards#41]
The person dealing with the printer(s) isn't always listed as an organizer.

Is there any possibility for having scoretakers be able to use this tool or even anyone to be able to search for a competition and print rounds for that competition?

**Comment by Goosly** [comment]
Hi @IldenH ,

I've added a field so you can enter any competition ID and get those scorecards: 
![image](https://github.com/user-attachments/assets/b48bd3f9-5c83-4965-b45b-5f4b5b7a8790)

Important note: as explained on the tool, whenever the scoretaker opens new rounds in Wca live, they need to sync and then refresh in the scorecard tool. If these are different persons, the printer person will need to ask the scoretaker to sync every time.
